trigger:
  branches:
    include:
      - main
      - dev

pr:
  branches:
    include:
      - main

parameters:
  - name: name
    type: string
    default: 'fastapi-opencensus'
  - name: appPort
    type: string
    default: '8000'
  - name: dockerRegistryUrl
    type: string
    default: 'https://index.docker.io'
  - name: dockerRegistryUsername
    type: string
    default: mauwii
  - name: dockerTag
    type: string
    default: $(Build.BuildId)
  - name: resourceLocation
    type: string
    default: 'westeurope'

${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
  variables:
    DEVTAG: '-dev'

steps:
  - task: Docker@2
    displayName: build Container
    inputs:
      containerRegistry: 'docker-mauwii'
      repository: '${{ parameters.dockerRegistryUsername }}/${{ parameters.name }}'
      command: 'build'
      Dockerfile: './Dockerfile'
      tags: |
        latest$[variables.DEVTAG]
        ${{ parameters.dockerTag }}
      arguments: '--build-arg=APP_PORT=${{ parameters.appPort }}'

  - task: Docker@2
    displayName: push Container
    inputs:
      containerRegistry: 'docker-mauwii'
      repository: '${{ parameters.dockerRegistryUsername }}/${{ parameters.name }}'
      command: 'push'
      tags: |
        latest$[variables.DEVTAG]
        ${{ parameters.dockerTag }}

  - task: AzureCLI@2
    displayName: create Resourcegroup
    inputs:
      azureSubscription: azure-mauwii
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az group create \
          --resource-group ${{ parameters.name }} \
          --location ${{ parameters.resourceLocation }}

  - task: AzureCLI@2
    displayName: preflight validation
    inputs:
      azureSubscription: azure-mauwii
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment group what-if \
          --resource-group ${{ parameters.name }} \
          --template-file main.bicep \
          --parameters \
            name=${{ parameters.name }} \
            dockerRegistryUrl=${{ parameters.dockerRegistryUrl }} \
            dockerRegistryUsername=${{ parameters.dockerRegistryUsername }} \
            websitePort=${{ parameters.appPort }} \
            tag=${{ parameters.dockerTag }}

  - task: AzureCLI@2
    displayName: deplyo Resources
    inputs:
      azureSubscription: azure-mauwii
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment group create \
          --resource-group ${{ parameters.name }} \
          --template-file main.bicep \
          --parameters \
            name=${{ parameters.name }} \
            dockerRegistryUrl=${{ parameters.dockerRegistryUrl }} \
            dockerRegistryUsername=${{ parameters.dockerRegistryUsername }} \
            websitePort=${{ parameters.appPort }} \
            tag=${{ parameters.dockerTag }}
