trigger:
  branches:
    include:
      - main
      - dev

pr:
  branches:
    include:
      - main

parameters:
  - name: name
    type: string
    default: 'fastapi-opencensus'
  - name: containerPort
    type: string
    default: '8080'
  - name: containerRegistryUrl
    type: string
    default: 'https://index.docker.io'
  - name: containerRegistryUsername
    type: string
    default: mauwii
  - name: containerTag
    type: string
    default: $(Build.BuildId)
  - name: resourceLocation
    type: string
    default: 'westeurope'

variables:
  - name: repository
    value: '${{ parameters.containerRegistryUsername }}/${{ parameters.name }}'
  - name: tag
    value: '${{ parameters.containerTag }}'
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
      - name: devtag
        value: '-dev'

steps:
  - task: Cache@2
    displayName: Cache task
    inputs:
      key: 'docker | "$(Agent.OS)" | cache'
      path: $(Pipeline.Workspace)/docker
      cacheHitVar: CACHE_RESTORED

  - script: |
      docker load -i $(Pipeline.Workspace)/docker/cache.tar
    displayName: Docker restore
    condition: and(not(canceled()), eq(variables.CACHE_RESTORED, 'true'))

  - task: Docker@2
    displayName: build Container
    inputs:
      containerRegistry: 'docker-mauwii'
      repository: '$(repository)'
      command: 'build'
      Dockerfile: './Dockerfile'
      tags: |
        latest${{ variables.devtag }}
        $(tag)
      arguments: '--build-arg=PORT=${{ parameters.containerPort }}'

  - script: |
      mkdir -p $(Pipeline.Workspace)/docker
      docker save -o $(Pipeline.Workspace)/docker/cache.tar $(repository):$(tag)
    displayName: Docker save
    continueOnError: true
    condition: and(not(canceled()), or(failed(), ne(variables.CACHE_RESTORED, 'true')))

  - task: Docker@2
    displayName: push Container
    inputs:
      containerRegistry: 'docker-mauwii'
      repository: '$(repository)'
      command: 'push'
      tags: |
        latest${{ variables.devtag }}
        $(tag)

  - task: AzureCLI@2
    displayName: create Resourcegroup
    inputs:
      azureSubscription: azure-mauwii
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az group create \
          --resource-group ${{ parameters.name }} \
          --location ${{ parameters.resourceLocation }}

  - task: AzureCLI@2
    displayName: preflight validation
    inputs:
      azureSubscription: azure-mauwii
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment group what-if \
          --resource-group ${{ parameters.name }} \
          --template-file main.bicep \
          --parameters \
              name=${{ parameters.name }} \
              containerRegistryUrl=${{ parameters.containerRegistryUrl }} \
              containerRegistryUsername=${{ parameters.containerRegistryUsername }} \
              containerPort=${{ parameters.containerPort }} \
              containerTag=$(tag)

  - task: AzureCLI@2
    displayName: deplyo Resources
    inputs:
      azureSubscription: azure-mauwii
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment group create \
          --resource-group ${{ parameters.name }} \
          --template-file main.bicep \
          --parameters \
              name=${{ parameters.name }} \
              containerRegistryUrl=${{ parameters.containerRegistryUrl }} \
              containerRegistryUsername=${{ parameters.containerRegistryUsername }} \
              containerPort=${{ parameters.containerPort }} \
              containerTag=$(tag)
